### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by HDVinnie** [bug-me-not/XBTIT-Blu-Edition-by-BluCrew#1]
Can you please remove the following from readme.

Demo Site: http://blu-edition.hdinnovations.xyz/index.php
Username: Demo 
Pass: Demo123.
Gitter Page: https://gitter.im/XBTIT-Blu-Edition/Lobby# Come chat with us!

Change:
In your web directory of the script.OPEN /sql/database.sql and goto line 7511 ('url', 'http://blu-edition.hdinnovations.xyz'), REPLACE WITH YOUR DOMAIN NAME! AND SAVE THE CHANGES.
to
In your web directory of the script.OPEN /sql/database.sql and goto line 7511 ('url', 'http://example.com'), REPLACE WITH YOUR DOMAIN NAME! AND SAVE THE CHANGES.

and remove Mr.Robot@stealth.tg from enforcement section. along with http://hdinnovations.xyz from description. Thanks

**Comment by bug-me-not** [comment]
Done :+1:
